name:  trigger Name
# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches: ["deploy"]
jobs:
  deploy:
    runs-on: ubuntu-latest # Run this job on the latest Ubuntu version

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Check out your repository code

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
        run: |
          echo "$PRIVATE_KEY"
          echo "$PRIVATE_KEY" > private_key # Write the private key to a file
          chmod 600 private_key # Set the appropriate permissions for the key file

          # Establish an SSH connection and execute commands on the remote server
          ssh -o StrictHostKeyChecking=no -i private_key -t root@194.87.54.16 <<EOF
            # Your server commands go here. Replace these commands with those relevant to your project.

            cd  /angular-tutorial
            git checkout origin deploy
            git pull
            npm run i 
          EOF

          rm -f private_key.pem # Remove the private key file after use for security
    permissions:
      contents: read
      actions: write
      id-token: write