name: CI
on:
  push:
    branches: ["dev"]
    tags: ["*"]
  pull_request:
    branch: ["dev"]
  
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        run: actions/setup-node@v4.2.0
      - name: Install package
        run: npm i
      
      - name: Formatting
        run: npm run prettier:fix:all
